apiVersion: v1
kind: Secret
metadata:
        name: mysecret

data:
     team_id: NTU0YjBjZjUtZmE4Yi01NmQxLWIxZTctZjk3MWExYmI1MThjCg==
     secret_key: Yjc2ODE4NGYtYjhkNy00NmRhLWE4MTgtNGZiOGQ3ZDZkYTNjCg== 

        

