---
# tasks file for multi-tier
- name: "--creating the kubernetes repo--"
  copy:
       dest: /etc/yum.repos.d/
       src: kubernetes.repo
- name: "--editing the network policy--"
  copy:
       dest: /etc/sysctl.d/k8s.conf
       content: |
              net.bridge.bridge-nf-call-ip6tables=1
              net.bridge.bridge-nf-call-iptables=1
- name: "--updating the network policy--"  
  command: sysctl --system
- name: "--installing the packages required to setup master--"
  package:
        name:
            - docker
            - kubeadm
            - iproute-tc
        state: present
- name: "changing the configuration of docker in master"
  copy:
        dest: /etc/docker/daemon.json
        content: |
                 {
                    "exec-opts":["native.cgroupdriver=systemd"]
                  }

- name: "--starting the service of docker and kubelet--"
  service:
          name: "{{ item }}"
          state: started
          enabled: yes
  loop:
        - docker
        - kubelet

- name: "--installing the required images--"
  command: kubeadm config images pull
- name: "--fetching public ip--"
  command: curl ifconfig.me
  register: ip 
- name: "--Launching all the containers--"
  command: kubeadm init --pod-network-cidr=10.244.0.0/16 --ignore-preflight-errors=NumCpu --control-plane-endpoint="{{ ip.stdout }}"  --ignore-preflight-errors=Mem
- name: "--creating user--"
  shell: "{{ item }}"
  loop:
           - mkdir -p $HOME/.kube
           - sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
           - chown $(id -u):$(id -g) $HOME/.kube/config
- name: "creating token for worker nodes"
  command: kubeadm token create --print-join-command
  register: token
- name: "creating overlay network"
  command: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
- debug:
        msg: "********Master has been setup successfully********"
